# config/zed2i_yaml
# Parameters for Stereolabs zed2i camera
---
/**:
    ros__parameters:
        general:
            camera_model: 'zed2i'
            camera_name: 'zed2i' # usually overwritten by launch file
            grab_resolution: 'VGA' # The native camera grab resolution. 'HD2K', 'HD1080', 'HD720', 'VGA', 'AUTO'
            grab_frame_rate: 60 # ZED SDK internal grabbing rate

        depth:
            min_depth: 0.5 # Min: 0.3, Max: 3.0
            max_depth: 5.5 # Max: 20

