# config/zedm_yaml
# Parameters for Stereolabs ZED mini camera
---
/**:
    ros__parameters:
        general:
            camera_model: 'zedm'
            camera_name: 'zedm' # usually overwritten by launch file
            grab_resolution: 'HD720' # The native camera grab resolution. 'HD2K', 'HD1080' = 1920x1080, 'HD720' = 1280x720, 'VGA' = 672x376, 'AUTO'
            grab_frame_rate: 30 # ZED SDK internal grabbing rate
            pub_resolution: 'CUSTOM' # The resolution used for image and depth map publishing. 'NATIVE' to use the same `general.grab_resolution` - `CUSTOM` to apply the `general.pub_downscale_factor` downscale factory to reduce bandwidth in transmission
            pub_downscale_factor: 2.0 # rescale factor used to rescale image before publishing when 'pub_resolution' is 'CUSTOM'
            pub_frame_rate: 30.0 # frequency of publishing of visual images and depth images

        depth:
            depth_mode: 'NEURAL_LIGHT'
            min_depth: 0.3 # Min: 0.1, Max: 3.0
            max_depth: 5.5 # Max: 10.0

        pos_tracking:
            pos_tracking_enabled: true # True to enable positional tracking from start
            pos_tracking_mode: 'GEN_3' # Matches the ZED SDK setting: 'GEN_1', 'GEN_2', 'GEN_3'