# Common configuration for PX4 autopilot
#
/**:
  ros__parameters:
    startup_px4_usb_quirk: true

# sys_status
/**/sys:
  ros__parameters:
    min_voltage: [10.0]   # diagnostics min voltage, use a vector i.e. [16.2, 16.0] for multiple batteries, up-to 10 are supported to achieve the same on a ROS launch file do: <rosparam param="sys/min_voltage">[16.2, 16.0]</rosparam>
    disable_diag: false # disable all sys_status diagnostics, except heartbeat
    heartbeat_rate: 1.0    # send heartbeat rate in Hertz
    conn_timeout: 10.0          # heartbeat timeout in seconds

# sys_time
/**/time:
  ros__parameters:
    time_ref_source: fcu  # time_reference source
    timesync_mode: MAVLINK
    timesync_avg_alpha: 0.6 # timesync averaging factor
    timesync_rate: 10.0    # TIMESYNC rate in Hertz (feature disabled if 0.0)
    system_time_rate: 1.0  # send system time to FCU rate in Hertz (disabled if 0.0)

# --- mavros plugins (alphabetical order) ---

# 3dr_radio
/**/tdr_radio:
  ros__parameters:
    low_rssi: 40  # raw rssi lower level for diagnostics

# actuator_control
# None

# command
/**/cmd:
  ros__parameters:
    use_comp_id_system_control: false # quirk for some old FCUs

# dummy
# None

# ftp
# None

# global_position
/**/global_position:
  ros__parameters:
    frame_id: "map"             # origin frame
    child_frame_id: "base_link" # body-fixed frame
    rot_covariance: 99999.0   # covariance for attitude?
    gps_uere: 1.0             # User Equivalent Range Error (UERE) of GPS sensor (m)
    use_relative_alt: true    # use relative altitude for local coordinates
    tf:
      send: false                 # Broadcast TF
      frame_id: "map"             # Parent frame is map
      child_frame_id: "base_link" # Child frame is base_link
      send_fcu: false             # Keep disabled

# imu_pub
/**/imu:
  ros__parameters:
    frame_id: base_link
    # need find actual values
    linear_acceleration_stdev: 0.0003
    angular_velocity_stdev: 0.0003490659 # 0.02 degrees
    orientation_stdev: 1.0
    magnetic_stdev: 0.0

# local_position
/**/local_position:
  ros__parameters:
    frame_id: "odom"              # origin frame
    tf:
      send: true                  # Broadcast TF
      frame_id: "odom"            # Parent frame is odom
      child_frame_id: "base_link" # Child frame is base_link
      send_fcu: false             # Keep disabled

# param
# None, used for FCU params

# rc_io
# None

# setpoint_accel
/**/setpoint_accel:
  ros__parameters:
    send_force: false

# setpoint_attitude
/**/setpoint_attitude:
  ros__parameters:
    reverse_thrust: false     # allow reversed thrust
    use_quaternion: false     # enable PoseStamped topic subscriber
    tf:
      listen: false
      frame_id: "map"
      child_frame_id: "target_attitude"
      rate_limit: 50.0

/**/setpoint_raw:
  ros__parameters:
    thrust_scaling: 1.0       # used in setpoint_raw attitude callback.
    # Note: PX4 expects normalized thrust values between 0 and 1, which means that
    # the scaling needs to be unitary and the inputs should be 0..1 as well.

# setpoint_position
/**/setpoint_position:
  ros__parameters:
    tf:
      listen: false
      frame_id: "map"
      child_frame_id: "target_position"
      rate_limit: 50.0
    mav_frame: LOCAL_NED

# setpoint_velocity
/**/setpoint_velocity:
  ros__parameters:
    mav_frame: LOCAL_NED

# vfr_hud
# None

# waypoint
/**/mission:
  ros__parameters:
    pull_after_gcs: true  # update mission if gcs updates
    use_mission_item_int: true # use the MISSION_ITEM_INT message instead of MISSION_ITEM
                               # for uploading waypoints to FCU


# --- mavros extras plugins (same order) ---

# adsb
# None

# debug_value
# None


# landing_target
/**/landing_target:
  ros__parameters:
    listen_lt: false
    mav_frame: "LOCAL_NED"
    land_target_type: "VISION_FIDUCIAL"
    image:
      width: 640
      height: 480
    camera:
      fov_x: 2.0071286398
      fov_y: 2.0071286398
    tf:
      send: true
      listen: false
      frame_id: "landing_target"
      child_frame_id: "camera_center"
      rate_limit: 10.0
    target_size:
      x: 0.3
      y: 0.3

# mount_control
/**/mount:
  ros__parameters:
    debounce_s: 4.0
    err_threshold_deg: 10.0
    negate_measured_roll: false
    negate_measured_pitch: false
    negate_measured_yaw: false

# odom
/**/odometry:
  ros__parameters:
    fcu:
      odom_parent_id_des: "map"      # desired parent frame rotation of the FCU's odometry
      odom_child_id_des: "base_link" # desired child frame rotation of the FCU's odometry

# vision_pose_estimate
/**/vision_pose:
  ros__parameters:
    tf:
      listen: false
      frame_id: "odom"
      child_frame_id: "vision_estimate"
      rate_limit: 10.0

# vision_speed_estimate
/**/vision_speed:
  ros__parameters:
    listen_twist: true    # enable listen to twist topic, else listen to vec3d topic
    twist_cov: true       # enable listen to twist with covariance topic

# camera
/**/camera:
  ros__parameters:
    frame_id: "base_link"

# distance_sensor
## Currently available orientations:
#    Check http://wiki.ros.org/mavros/Enumerations
##
/**/distance_sensor:
  ros__parameters:
    config: |
      hps167_pub:
        id: 0
        frame_id: "hps167_frame"
        # orientation: PITCH_270  # sended by FCU
        field_of_view: 0.0        # XXX TODO
        send_tf: true
        sensor_position: {x:  0.0, y:  0.0, z:  -0.1}