/**:
  ros__parameters:
    # src/path_planning_module/planner_manager/include/ego_planner_component.cpp
    planner:
      flight_height: 2.0
      planner_freq: 50.0  # in Hz (25 ~ 100)
      collision_check_freq: 25.0
      max_vel: 0.75
      max_acc: 2.0
      orbit_flight_height: 2.0
      orbit_max_vel: 0.5
      orbit_max_acc: 1.5
      emergency_time: 0.8
      replan_threshold: 1.0
      global_retrials: 10
      local_retrials: 1
      poly_traj_piece_length: 1.0
      feasibility_tolerance: 0.05
      planning_horizon: 5.50
      use_multitopology_trajs: false
      drone_id: 0
      enable_diagnostics: false
    # src/path_planning_module/grid_map/src/grid_map.cpp
    grid_map:
      resolution: 0.1
      min_clearance: 0.3
      local_update_range_x: 5.5
      local_update_range_y: 5.5
      local_update_range_z: 3.5
      obstacles_inflation: 0.12
      enable_virtual_wall: true
      virtual_ceil: 5.0  # Note: Must be bigger than flight height!!
      virtual_ground: -0.1
      p_hit: 0.70
      p_miss: 0.30
      p_min: 0.12
      p_max: 0.97
      p_occ: 0.80
      fading_time: 10.0
      frame_id: "map"
      visualize_rate: 1.0
      fading_rate: 1.0
      max_cloud_range: 5.5
      confidence_near_range: 2.0
      confidence_far_range: 5.5
      min_confidence_weight: 0.3
      max_lidar_range: 15.0
      trunk_extrude_height: 0.0
      laser_frame: "laser"
    # src/path_planning_module/planner_utils/src/plan_visualizer.cpp
    visualizer:
      frame_id: "map"
    # src/path_planning_module/planner_utils/src/poly_traj_optimizer.cpp
    optimization:
      constraint_points_per_piece: 5
      weight_obstacle: 10000.0
      weight_obstacle_soft: 5000.0
      weight_swarm: 10000.0
      weight_feasibility: 10000.0
      weight_sqrvariance: 10000.0
      weight_time: 10.0
      obstacle_clearance: 0.35
      obstacle_clearance_soft: 0.5
      swarm_clearance: 0.15
      max_vel: 0.75
      max_acc: 2.0
      max_jer: 10.0
